pluginGroup = com.gmail.blueboxware
pluginName = LibGDX
pluginVersion = 1.29

# https://www.jetbrains.com/intellij-repository/snapshots/
# https://www.jetbrains.com/intellij-repository/releases/
# gradle printProductsReleases

platformVersion = 253.32098.37
#platformVersion = 261.24374.151

platformBundledPlugins = com.intellij.java, org.jetbrains.kotlin, com.intellij.properties, com.intellij.modules.json, com.intellij.modules.platform
platformBundledModules = tanvd.grazi, intellij.spellchecker, intellij.properties.backend.psi, intellij.properties.backend

kotlin.stdlib.default.dependency = false

kotlin.daemon.jvmargs=-Xmx4g
org.gradle.jvmargs=-Xmx4g

org.jetbrains.intellij.platform.downloadSources=true

org.gradle.configuration-cache = true
org.gradle.caching = true
